spring:
  application:
    name: ACCP
  jackson:
    # 忽略所有 null 字段
    default-property-inclusion: non_null
  #数据库的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accp
    username: root
    password: yyj060730
  profiles:
    active: prod
  #redis缓存配置信息
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100
  mail:
    # 邮件服务器主机（QQ邮箱：smtp.qq.com；163邮箱：smtp.163.com；Gmail：smtp.gmail.com）
    host: smtp.163.com
    # 邮箱端口（SSL加密端口：465；非加密：587，推荐465）
    port: 465
    # 发件人邮箱账号
    username: accp_official@163.com
    # 邮箱授权码（重点：不是登录密码，需在邮箱后台开启SMTP获取）
    password: WVbhz37BETmhYhfQ
    # 编码格式
    default-encoding: UTF-8
    # SSL加密配置（必须配置，否则连接失败）
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

#Mybatis的相关配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml